- name: mac setup v1
  hosts: localhost
  gather_facts: yes
  become: no

  roles:
    - role: homebrew
      tags: homebrew
    - role: zsh
      tags: zsh
    - role: dotfiles
      tags: dotfiles
    - role: intellij
      tags: intellij
    - role: dock
      tags: dock

  # tasks:
  #   - name: Create projects dir
  #     file:
  #       path: "{{ ansible_env.HOME }}/Projects"
  #       state: directory
    
  #   - name: setup dotfiles
  #     import_role:
  #       name: dotfiles
  #   - name: Don’t display the annoying prompt when quitting iTerm
  #     tags: macos
  #     osx_defaults:
  #       domain: com.googlecode.iterm2
  #       key: PromptOnQuit
  #       type: int
  #       value: "0"