- name: mac setup v1
  hosts: all
  gather_facts: yes
  become: no

  roles:
    - role: homebrew
      tags: homebrew
    - role: zsh
      tags: zsh
    - role: dotfiles
      tags: dotfiles
    - role: jetbrains
      tags: jetbrains
    - role: dock
      tags: dock
    - role: sdks
      tags: sdks
    - role: osx_defaults
      tags: osx_defaults
