---
roles:
  - name: elliotweiser.osx-command-line-tools
  - name: gantsign.intellij-plugins
  - name: Comcast.sdkman
  - name: suzuki-shunsuke.gvm
    version: v6.0.0

collections:
  - name: geerlingguy.mac
