---
# tasks file for dotfiles

- name: set variable file
  include_vars: "vars/{{ var_file_name }}.yml"

# todo, file permissions
- name: create zshrc in home dir
  template:
    src: zshrc.j2
    dest: "{{ ansible_env.HOME }}/.zshrc"
    #backup: true
    mode: 0640

- name: create zsh_plugins in home dir
  template:
    src: zsh_plugins.j2
    dest: "{{ ansible_env.HOME }}/.zsh_plugins.txt"
    #backup: true
    mode: 0640

- name: create gitconfig in home dir
  template:
    src: gitconfig.j2
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    #backup: true
    mode: 0640

- name: copy dircolor config in place
  copy:
    src: .dircolors
    dest: "{{ ansible_env.HOME }}/.dircolors"
    # backup: yes
    mode: 0640

# TODO
# - name: copy karabiner config
#   copy:
#     src: remap_command_h_intellij.json
#     dest: "{{ ansible_env.HOME }}/.config/karabiner/assets/complex_modifications/remap_command_h_intellij.json"
#     # backup: yes
#     mode: 0640
    