---
# tasks file for dock

- name: set variable file
  include_vars: "vars/{{ var_file_name }}.yml"

# TODO only works localhost, will have to run multiple times as well
- name: Setup dock
  include_role:
    name: geerlingguy.mac.dock
