---
# tasks file for sdks

- name: Install sdkman
  include_role:
    name: Comcast.sdkman
  vars:
    sdkman_auto_answer: true
    sdkman_update: true
    sdkman_install_packages:
      - { candidate: java, version: 11.0.11.hs-adpt }
      - { candidate: gradle, version: 7.2 }
      - { candidate: maven, version: 3.8.3 }
    sdkman_defaults:
      gradle: '7.2'
      maven: 3.8.3
      java: 11.0.11.hs-adpt
    sdkman_flush_caches_before:
      - temp
    sdkman_flush_caches_after:
      - archives
      - broadcast
      - candidates
      - temp
    sdkman_offline_mode: false
      