---
# tasks file for homebrew

# https://github.com/geerlingguy/ansible-collection-mac/blob/master/roles/homebrew/README.md


- name: Install homebrew
  include_role:
    name: geerlingguy.mac.homebrew
  vars:
    mas_installed_app_ids:
      - 937984704 # Amphetamine
  #   - 424389933 # Final Cut Pro
  #   - 497799835 # Xcode

    homebrew_taps:
      - adoptopenjdk/openjdk
      - homebrew/cask
      - caskroom/fonts
      # - homebrew/cask-versions

    homebrew_installed_packages:
      - git
      - bash
      - coreutils
      - gawk
      - htop
      - gnu-sed
      - zsh
      - zsh-completion
      - antibody
      - zlib
      - pyenv
    
    homebrew_upgrade_all_packages: false

    homebrew_cask_apps:
      # - docker
      # - firefox
      # - iterm2
      # - slack
      # - macfuse
      # - unetbootin
      - mullvadvpn
      # - intellij-idea
      - intellij-ide-ce
      # - goland
      - vlc
      # - boostnote
      # - postman
      - alt-tab
      - karabiner-elements
      - font-hack-nerd-font
