---
# tasks file for homebrew

# https://github.com/geerlingguy/ansible-collection-mac/blob/master/roles/homebrew/README.md

- name: set variable file
  include_vars: "vars/{{ var_file_name }}.yml"

- name: Install homebrew
  include_role:
    name: geerlingguy.mac.homebrew
  vars:
    homebrew_installed_packages: "{{ general_homebrew_installed_packages + host_homebrew_installed_packages }}"
    homebrew_cask_apps: "{{ general_homebrew_cask_apps + host_homebrew_cask_apps }}"

# - name: Install app store apps
#   include_role:
#     name: geerlingguy.mac.mas
      