---
# tasks file for homebrew

# https://github.com/geerlingguy/ansible-collection-mac/blob/master/roles/homebrew/README.md

# - name: get task vars
#   include_vars: 
#     dir: vars
#     name: test
    # ignore_files:
    #  - personal.yml

- name: Install homebrew
  include_role:
    name: geerlingguy.mac.homebrew
      
