---
# tasks file for osx_defaults

- name: Don’t display the annoying prompt when quitting iTerm
  tags: macos
  osx_defaults:
    domain: com.googlecode.iterm2
    key: PromptOnQuit
    type: int
    value: "0"
    