---
# tasks file for osx_defaults

- name: Don’t display the annoying prompt when quitting iTerm
  osx_defaults:
    domain: com.googlecode.iterm2
    key: PromptOnQuit
    type: int
    value: "0"
    
# not working in big sir
# - name: Disable the "Are you sure you want to open this application?" dialog
#   osx_defaults:
#     domain: com.apple.LaunchServices
#     key: LSQuarantine
#     type: int
#     value: "0"

- name: Show hidden files by default
  osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: boolean
    value: "true"

- name: Show all filename extensions
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: boolean
    value: "true"

- name: Allow text selection in Quick Look 
  osx_defaults:
    domain: com.apple.finder
    key: QLEnableTextSelection
    type: boolean
    value: "true"

- name: Disable the warning when changing a file extension
  osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: boolean
    value: "false"

- name: Always show the Dock
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: boolean
    value: "true"

- name: Avoid creating .DS_Store files on network volumes
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: boolean
    value: "true"

- name: Disable shadow in screenshots
  osx_defaults:
    domain: com.apple.screencapture
    key: disable-shadow
    type: boolean
    value: "true"

- name: Copy email addresses as `foo@example.com` instead of `Foo Bar <foo@example.com>` in Mail.app
  osx_defaults:
    domain: com.apple.mail
    key: AddressesIncludeNameOnPasteboard
    type: boolean
    value: "false"
